### ISSUE TITLE
libAnalytics.a 

### ISSUE THREAD

**Issue by hojberg** [smore-inc/react-native-segment-io-analytics#11]
Where can I find this file to link it?

**Comment by yelled3** [comment]
@talkain /cc

**Comment by talkain** [comment]
@hojberg Did you add the ```pod "Analytics"``` line to your Podfile?
after doing so, you need to close the project and run "pod install" again. (I will add it to the instructions)

**Comment by hojberg** [comment]
@talkain Thanks! I found it. The key was to use the workspace file (duh) :D

**Comment by jinxac** [comment]
Still facing this issue? Any suggestions? Cant find libAnayltics.a

**Comment by afilp** [comment]
Can you please, please remove the requirement to use POD?

It complicates matters (it is the only package that uses POD), all others use `react-native link`.

Thanks!

**Comment by jinxac** [comment]
after trying a lot i finally decided to go with [https://github.com/neiker/analytics-react-native](url) . It really works out of the box.
