### ISSUE TITLE
9 duplicate symbols for architecture x86_64

### ISSUE THREAD

**Issue by homanp** [smore-inc/react-native-segment-io-analytics#16]
Followed the install guide and all I get is this:

```
ld: 9 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Any ideas?

**Comment by homanp** [comment]
This is seems to be an issue related to Analytics cocoapod so closing this issue :)

**Comment by talkain** [comment]
@homanp Cool :) Can you please elaborate on that? Have you managed to solve the issue?
(Just wanted to add it to the "Handling possible issues" section)

Thanks in advance! :)

**Comment by homanp** [comment]
Well I tried installing the SegmentIO lib for iOS and get the same issue. I've contacted the SegementIO support and will update this issue as soon as I get an answer from them!

**Comment by talkain** [comment]
Thank you  :)

**Comment by homanp** [comment]
BTW, is this working for? Can you install Pod 'Analytics' without any issues?

**Comment by talkain** [comment]
@homanp Yes, I just tried it on a new clean project and everything worked well.

Here is my Podfile example:
```
platform :ios, '8.0'

xcodeproj 'ios/TESTER.xcodeproj'
target 'TESTER' do
pod 'Analytics', '~> 3.0.3'
end
```

Can you paste the error you are getting from the ```pod install``` command?

**Comment by homanp** [comment]
`pod install` works fine for me as well. No errors are thrown. It's when I build my app I get this error.
